config/routes.rb
UFABC::Application.routes.draw do

  resources :disciplines do
    resources :groups
  end
  resources :groups
  
  match 'best_timetable' => 'best_timetable#new', :as => 'best_timetable', :via => :get
  match 'best_timetable/generate' => 'best_timetable#generate', :as => 'generate_best_timetable', :via => :get

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  
  TPI_REGEX = /^(\d{1,2})-(\d{1,2})-(\d{1,2})$/
  CODE_REGEX = /\A(BC|MC|NH|EN|BH|CS)(\d{4})\Z$/
  
  #validates :tpi,  :format   => TPI_REGEX,  :presence => true
  validates :code, :format   => CODE_REGEX, :presence => true, :uniqueness => true
  validates :name, :length   => 1..70,      :presence => true

  has_many :groups
  
  def teoric_hours
    broken_tpi[0].to_i
  end
  
  def practical_hours
    broken_tpi[1].to_i
  end
  
  def individual_hours
    broken_tpi[2].to_i
  end
  
  private
  
  def broken_tpi
    @broken_tpi ||= tpi.scan(TPI_REGEX)[0]
  end
end

app/controllers/disciplines_controller.rb
#encoding: utf-8
class DisciplinesController < ApplicationController

  caches_action :index
  def new
    @discipline = Discipline.new
  end

  def create
    @discipline = Discipline.new(params[:discipline])
    @discipline.save!
    flash[:notice] = "A disciplina foi salva com sucesso!"
    expire_action :action => :index
    redirect_to :action => 'index'
  rescue ActiveRecord::RecordInvalid
    flash[:error] = "Houve erros ao tentar salvar a disciplina"
    render 'new'
  end

  def index
    @disciplines = Discipline.all
  end

  def show
    id = params[:id]
    @discipline = Discipline.find id
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "A disciplina com id #{id} não foi encontrada!"
    redirect_to disciplines_path
  end
end

app/views/disciplines/create.html.erb
<h1>Disciplines#create</h1>
<p>Find me in app/views/disciplines/create.html.erb</p>

app/views/disciplines/index.html.erb
<ul class="cool_list centered">
  <% @disciplines.each do |discipline| %>
    <%= link_to discipline  do -%>
        <li><span class="code"><%= discipline.code -%></span><span class="name"><%= discipline.name -%></span></li>
    <% end %>
  <% end %>
</ul>
<%= link_to "New discipline", new_discipline_path %>

app/views/disciplines/new.html.erb
<%= show_error_messages_for @discipline %>
<%= form_for(@discipline) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %><br />
  
  <%= f.label :code, "Code" %>
  <%= f.text_field :code %><br />
  
  <%= f.label :tpi, "TPI" %>
  <%= f.text_field :tpi %><br />
  
  <%= f.submit "Submit" %>
<% end %>

app/views/disciplines/show.html.erb
<h1><%= "#{@discipline.code} - #{@discipline.name}" %></h1>
<h2><%= "TPI: #{@discipline.tpi}" %></h2>
<h2>Groups:</h2>
<ul>
  <% @discipline.groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
</ul>
<%= link_to 'Add new group', new_discipline_group_path(@discipline) %>