config/routes.rb
UFABC::Application.routes.draw do

  resources :disciplines do
    resources :groups
  end
  resources :groups
  
  match 'best_timetable' => 'best_timetable#new', :as => 'best_timetable', :via => :get
  match 'best_timetable/generate' => 'best_timetable#generate', :as => 'generate_best_timetable', :via => :get

end

app/models/group.rb
require 'lesson_table_validator'

class Group < ActiveRecord::Base
  include GroupConstants

  belongs_to  :discipline

  validates :name,          :presence => true, :uniqueness => {:scope   => :discipline_id,
                                                               :message => "has been taken by another group on this discipline"}

  validates :discipline_id, :presence => true, :uniqueness => {:scope => WEEK_DAYS.map { |day| 'int_'+day.to_s},
                                                               :message => "already has another group with these lessons" }
  validates :lessons,       :presence => true, :lesson_table => true

  def lessons=(lesson)
    lesson = {} unless lesson.respond_to? '[]'
    week_days.each do |day|
      lesson[day] = day_hash_to_array(lesson[day]) if lesson[day].kind_of? Hash
      lesson[day] ||= Array.new
      self.send("int_#{day}=", IntTools.int_from_lessons(lesson[day]) )
    end
  end

  def lessons
    week_days.inject({}) do |hash, day|
      hash.merge Hash[day, IntTools.lessons_from_int(send "int_#{day}")]
    end
  end

  def collides_with?(group)
    week_days.each do |day|
      message = "int_#{day}".to_sym
      return true unless (send(message) & group.send(message))==0
    end
    return false
  end

  private

  def day_hash_to_array(day_hash)
    day_hash.reject{ |_, v| v.to_i==0 }.keys
  end

  def to_ary
    nil
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  caches_action :index
  def new
    @group = Group.new(:discipline_id => params[:discipline_id])
    @discipline_options = Discipline.all.map do |discipline|
      ["#{discipline.code} - #{discipline.name}", discipline.id]
    end
  end

  def create
    @group = Group.new(params[:group])
    @group.save!
    flash[:notice] = "A turma foi salva com sucesso!"
    expire_action :action => :index
    redirect_to @group
  rescue
    flash[:error] = "Houve erros ao tentar salvar a disciplina!"
    #TODO: Research refactor! D:
    @discipline_options = Discipline.all.map do |discipline|
      ["#{discipline.code} - #{discipline.name}", discipline.id]
    end
    render :action => :new
  end

  def show
    @group = Group.find(params[:id])
  end

  def index
    @groups = Group.all(:joins => :discipline, :order => 'disciplines.name')
  end

end

app/helpers/groups_helper.rb
require 'group_constants'
require 'int_tools'

module GroupsHelper
  include GroupConstants
end

app/views/groups/_lessons_input_form.erb
<%= render :layout => 'layouts/timetable_layout' do %>
  <% all_lessons.each do |lesson| %>
    <tr class="time"><td><%= lesson %></td><td colspan=6><hr /></td></tr>
    <tr><td />
        <% week_days.each do |day| %>
          <%= content_tag :td do %>
            <%= check_box_tag "group[lessons][#{day}][#{lesson}]" %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <% end %>

app/views/groups/index.html.erb
<ul class="cool_list centered">
<% @groups.sort_by { |g| g.discipline.name}.each do |group| %>
  <%= link_to group do -%>
    <li><span class="name"><%= group.discipline.name %></span><span class="group"><%= group.name %></span></li>
  <% end %>
<% end %>
</ul>
<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<%= show_error_messages_for @group %>
<%= form_for(@group) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %><br />
  
  <%= f.label :discipline_id, "Discipline" %>
  <%= f.select :discipline_id, @discipline_options %><br />
  
  <%= render :partial => "lessons_input_form" %>
  
  <%= f.submit "Submit" %>
  
<% end %>

app/views/groups/show.html.erb
<%= content_tag :h1, "#{@group.discipline.name} - #{@group.name}" %>
<%= render "shared/timetable", :groups => [@group] %>