config/routes.rb
UFABC::Application.routes.draw do

  resources :disciplines do
    resources :groups
  end
  resources :groups
  
  match 'best_timetable' => 'best_timetable#new', :as => 'best_timetable', :via => :get
  match 'best_timetable/generate' => 'best_timetable#generate', :as => 'generate_best_timetable', :via => :get

end

app/controllers/best_timetable_controller.rb
#encoding: utf-8
class BestTimetableController < ApplicationController
  include BestTimetableHelper

  caches_action :new
  def new
    @disciplines = Discipline.all
  end

  def generate
    if selected_codes.empty?
      flash[:error] = "Nenhuma disciplina foi selecionada!"
      redirect_to :action => :new
    elsif selected_codes.count>7
      flash[:error] = "Por favor, selecione no máximo 7 disciplinas"
      redirect_to :action => :new
    else
      @timetables = BestTimetable.generate Hash[chosen_disciplines]
      if @timetables.nil? or @timetables.empty?
        flash[:error] = "Não foi possível gerar nenhum horário! Seja menos restritivo e/ou cadastre mais turmas e tente novamente"
        redirect_to :action => :new
      end
    end
  end

  private

  def selected_codes
    disciplines = params[:disciplines] || {}
  end

  def chosen_disciplines
    selected_codes.map do |code, inclusion|
      discipline = Discipline.find_by_code code
      [discipline, inclusion]
    end
  end

end

app/helpers/best_timetable_helper.rb
module BestTimetableHelper

  def chosen_disciplines
    disciplines = params[:disciplines] || {}
    disciplines.keys.map do |code|
      Discipline.find_by_code code || next
    end
  end
end

app/views/best_timetable/generate.html.erb
<% @timetables.take(5).each.with_index do |timetable, index| %>
  <div class="timetable_div">
    <%= content_tag :h2, "#{index+1}º melhor horário:" %>
    <ul class="cool_list">
      <% timetable.groups.each do |group| %>
        <%= link_to group do -%>
          <li><span class="name"><%="#{group.discipline.code} - #{group.discipline.name}"%></span><span class="group"><%= "(#{group.name})"%></span></li>
        <% end %>
    <% end %>
    </ul>
    <div class="ghost_timetable">
      <%= render 'shared/timetable', :timetable => timetable %>
    </div>
  </div>
  <hr />
<% end %>

app/views/best_timetable/new.html.erb
<%= form_tag generate_best_timetable_path, :method => :get do %>
  <table id="disciplines_table">
    <tr><td></td><% %w{necessária opcional}.each do |option| %>
      <%= content_tag :td, option %>
    <% end %></tr>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= label_tag "disciplines_#{discipline.code}", "#{discipline.code} - #{discipline.name}" %></td>
        <% %w{required optional}.each do |option| %>
          <td><%= radio_button_tag "disciplines[#{discipline.code}]", option, false -%></td>
        <% end -%>
      </tr>
    <% end %>
  </table>
  <%= submit_tag 'Submit' %>
<% end %>