config/routes.rb
UFABC::Application.routes.draw do

  resources :disciplines do
    resources :groups
  end
  resources :groups
  
  match 'best_timetable' => 'best_timetable#new', :as => 'best_timetable', :via => :get
  match 'best_timetable/generate' => 'best_timetable#generate', :as => 'generate_best_timetable', :via => :get

end

app/views/layouts/_timetable_layout.html.erb
<table class="timetable centered">
  <thead>
    <tr>
      <td />
        <% %w{Segunda Terça Quarta Quinta Sexta Sábado}.each do |day| %>
          <%= content_tag :th, day.capitalize %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= yield %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<% cache do %>
  <!DOCTYPE html>
  <html>
    <head>
      <title>Gerador de Horários</title>
      <%= stylesheet_link_tag 'style' %>
      <%= csrf_meta_tag %>
    </head>
    <body>
      <div id="header">
        <ul id="menu">
          <li><%= link_to "Home", "/" %>
          <li><%= link_to "Gerar grade", best_timetable_path %></li>
          <li><%= link_to "Disciplinas", disciplines_path %></li>
          <li><%= link_to "Turmas", groups_path %></li>
          <li><%= link_to "Sobre", "#" %></li>
        </ul>
      </div>
      <a href="http://github.com/riccieri/Timetable-generator"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://d3nwyuy0nl342s.cloudfront.net/img/abad93f42020b733148435e2cd92ce15c542d320/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub"></a>
    <% end %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <div id="content" class="centered">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>